### ISSUE TITLE
How to add an initial user?

### ISSUE THREAD

**Issue by marcelkorpel** [etraxis/etraxis#130]
After transpiling all depencies and starting the server, like described in the README, I get a simple login screen. As that would not always be desirable, there is no sign-up form. Using legacy FOSUserBundle, one could add a new (initial) user using `bin/console fos:user:create`. However, I can't find how to do something similar with current Symfony Security.

The only thing I could find is `bin/console security:encode-password`, but there are many more fields in `user` table that need to be filled. It isn't likely that one is supposed to create an initial user this way, but I can't find the 'right' one.

**Comment by webinarium** [comment]
Hi Marcel,

Since you've read the README, I believe you're aware that the project is still under development, and you're asking just because you'd like to check it out early.

You are right - there is no signup form, as a self-signup is not supposed to be in the final product. Instead, any user with "admin" permissions can create additional accounts as required. The initial installaion will contain one required step:

`./bin/console doctrine:fixtures:load --group=prod`

which will create one predefined admin-account with 'admin@example.com' email and 'secret' as a password. At this stage, you can either run this command as specified, or skip the '--group=prod' part to load all the fixtures (there are a lot of them for testing purpose).

Please be aware - right now you will see only a blank page after the login, as the frontend part has just been started. Though, more pages to check out will come in a week or two. I'm attaching a couple of screenshots of what (roughly) to expect.

![issues-list](https://user-images.githubusercontent.com/741349/80338148-cb51a000-88af-11ea-9511-1f2586b2cd72.png)

![single-issue](https://user-images.githubusercontent.com/741349/80338157-cf7dbd80-88af-11ea-90ef-a94fc883d5d8.png)

**Comment by marcelkorpel** [comment]
Thanks for your answer. I'll have to admit that I'm not especially interested in eTraxis itself, how useful it looks (nice screenshots, BTW), but I'm planning to upgrade my own application from Symfony 4 and FOSUserBundle to the current Symfony (Security), so my apologies for "misusing" your application for my own purposes.

Now I know why I didn't have an initial user. When I tried to load fixtures, I got
```
   > purging database
   > loading eTraxis\DataFixtures\ProductionFixtures
   > loading eTraxis\DataFixtures\ProjectFixtures
   > loading eTraxis\DataFixtures\TemplateFixtures
   > loading eTraxis\DataFixtures\UserFixtures
   > loading eTraxis\DataFixtures\GroupFixtures
   > loading eTraxis\DataFixtures\TemplatePermissionFixtures
   > loading eTraxis\DataFixtures\StateFixtures
   > loading eTraxis\DataFixtures\IssueFixtures

In IssueFixtures.php line 205:
                                                               
  Notice: Trying to access array offset on value of type null  
                                                               
```
Apparently `$row['responsible']` is `null`, so a quick solution was to add `$row['responsible'] && …` in the condition (but this is of course a work around, I think). Now everything is in place.

Anyway, thanks again for your response!
