### ISSUE TITLE
Some more indexes

### ISSUE THREAD

**Issue by petrbrouzda** [etraxis/etraxis#6]
Our customer has a very complex View in eTraxis - many columns and many filters.
Displaying a list of records took about 25 seconds, which is almost unusable.

Log from this action can be found at:
http://lovecka.info/pb/dotaz.sql.txt
(I changed the formatting of SQL command in order it can be read by human)

I've added some more indexes and reduced execution time to almost half  (before it has cost 3491 / time 42, with added indexes it falled to cost 1503 / time 19; real execution time falled from 25 sec to about 15 sec).

create index ix_fva_comb2 on tbl_field_values ( field_id, value_id, is_latest, event_id );
create index ix_svl_id_val on tbl_string_values ( value_id, string_value );
create index ix_rds_comb on  tbl_reads (record_id, account_id, read_time);
create index ix_lvl_id_val on tbl_list_values ( field_id, int_value, str_value );

The most effect came from the ix_fva_comb2, the other indexes are much less valuable.

(Oracle database - I don't know if the effect would be the same on other DB engines).

By the way:
According to my previous experiences I recommend to split this mega-command into two commands:
1) The first SQL command would search for records (by filters, search query and so on) and return basic informations from TBL_RECORDS only (no user defined fields) - and should return ONLY records that has to be displayed on current page (so it will read for example rows 100-120 only - how to do this is described here: http://troels.arvin.dk/db/rdbms/#select-limit-offset). So it will return maximum of (page-length) records, not hundreds nor thousands of records as it does now.
2) Second SQL command would get list of IDs of records (returned from command 1) as parameter and should render the columns based on current view settings. It will work on current-page-records only (so up to 20 records by default).
Doing that split in eTraxis 4 would bring a big performace improvement. Command described in step 1 will probably run at about the same speed as now, but it will do pagination - so you'll not need to fetch all of the records as you do now in records/list.php (= small performance improvement).  But the step 2 command will bring a BIG performace gain - will work on page-size count of records only instead of current hudreds of records.

**Comment by webinarium** [comment]
Thank you for the proposal, I have committed new indexes and will release them in the next version.

**Comment by webinarium** [comment]
Regarding the split you have advised. I thought about it, but there are few blockers to do that:
1. User can sort his view by custom field, which means that first query (which should produce only limited subset of IDs) must include this custom field to order the results appropriately.
2. The above can be partially addressed, if we will add such custom field only when user uses it to sort by. But, while currently user can sort only by one column, in the future it will be multi-columns sorting, which means that in some cases first query can contain all custom fields. In other words, worst case will be exactly the same as the current situation.

Taking the above into consideration, I would like to find other ways to improve the performance. For custom fields it should be appropriate indexes, and maybe some data schema refactoring (it might be overnormalized at the moment).

By the way, the search is even worse, because it uses "LIKE" statement to search in custom fields - I consider to introduce support for ElasticSearch into the project.
